name: "NexusShift"
main: "io.github.nexuskrop.nexusshift.NexusShift"
version: 0.1.1

description: "NexusShift main plugin"
author: NexusKrop
api-version: 1.18

website: "https://github.com/NexusKrop/NexusShift"